apiVersion: v1
name: descheduler
description: descheduler chart that runs on kubernetes
version: 1.0.8
keywords:
  - descheduler
  - kubernetes
home: https://github.com/stakater-charts/descheduler
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
