apiVersion: v1
metadata:
  name: {{ template "name" . }}-policy-configmap
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
kind: ConfigMap
data:
  policy.yaml: |-
{{ .Values.descheduler.config.policy | indent 4 }}
