apiVersion: v1
metadata:
  name: {{ template "descheduler.name" . }}-policy-configmap
  labels:
{{ include "descheduler.labels.stakater" . | indent 4 }}
{{ include "descheduler.labels.chart" . | indent 4 }}
kind: ConfigMap
data:
  policy.yaml: |-
{{ .Values.descheduler.config.policy | indent 4 }}
