apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "descheduler.name" . }}
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: "true"
spec:
# Every 6 Hours
  schedule: "{{ .Values.descheduler.job.schedule }}"
  jobTemplate:
    spec:
      parallelism: {{ .Values.descheduler.job.parallelism }}
      completions: {{ .Values.descheduler.job.completions }}
      template:
        metadata:
          labels:
{{ include "descheduler.labels.stakater" . | indent 12 }}
{{ include "descheduler.labels.chart" . | indent 12 }}
          name: {{ template "descheduler.name" . }}-pod
          annotations:
            scheduler.alpha.kubernetes.io/critical-pod: "true"
        spec:
            containers:
            - name: {{ template "descheduler.name" . }}
              image: "{{ .Values.descheduler.image.name }}:{{ .Values.descheduler.image.tag }}"
              volumeMounts:
              - mountPath: /policy-dir
                name: policy-volume
              command:
              - "/bin/sh"
              - "-ec"
              - "/bin/descheduler -v 2 --policy-config-file /policy-dir/policy.yaml"
            restartPolicy: "{{ .Values.descheduler.job.restartPolicy }}"
            serviceAccountName: {{ template "descheduler.name" . }}-sa
            volumes:
            - name: policy-volume
              configMap:
                name: {{ template "descheduler.name" . }}-policy-configmap
